# See AppVeyor.yml reference:
# https://www.appveyor.com/docs/appveyor-yml/

version: 2018.1.{build}-{branch}

only_commits:
  author: richard.goulter@gmail.com

image:
  - Visual Studio 2017

platform:
  - x64

configuration: Release

before_build:
  - cmd: set PATH=%PATH%;C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1;
  - cmd: choco install gradle -y

build_script:
  - gradle build distZip
